
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials[:dbuser] %>
  password: <%= Rails.application.credentials[:dbpassword] %>

development:
  <<: *default
  database: schtweet_dev4
  encoding: unicode  

test:
  <<: *default
  database: schtweet_test4
  encoding: unicode

production:
  <<: *default
  database: scheduledtweets
  encoding: unicode
  username: scheduledtweets_user
  password: <%= Rails.application.credentials[:renderpassword] %>
